# Generated by Django 5.0.3 on 2024-04-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winning',
            field=models.BooleanField(default=False),
        ),
    ]
