# Generated by Django 5.0.3 on 2024-04-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default='default_category_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
