# Generated by Django 5.0.3 on 2024-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default='default_category_name', max_length=50, null=True),
        ),
    ]
