# Generated by Django 5.0.3 on 2024-04-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winning',
        ),
    ]
