# Generated by Django 5.0.3 on 2024-04-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_bid_winning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
    ]
